import FluentAdd32Filled from "~icons/fluent/add-32-filled";
import FluentChevronCircleDown32Filled from "~icons/fluent/chevron-circle-down-32-filled";
import FluentChevronCircleUp32Filled from "~icons/fluent/chevron-circle-up-32-filled";
import FluentChevronDown32Filled from "~icons/fluent/chevron-down-32-filled";
import FluentChevronLeft32Filled from "~icons/fluent/chevron-left-32-filled";
import FluentChevronRight32Filled from "~icons/fluent/chevron-right-32-filled";
import FluentChevronUp32Filled from "~icons/fluent/chevron-up-32-filled";
import FluentDismiss32Filled from "~icons/fluent/dismiss-32-filled";
import FluentEdit32Filled from "~icons/fluent/edit-32-filled";
import FluentNavigation32Filled from "~icons/fluent/navigation-32-filled";
import FluentPin32Filled from "~icons/fluent/pin-32-filled";
import FluentPinOff32Filled from "~icons/fluent/pin-off-32-filled";
import FluentSave32Filled from "~icons/fluent/save-32-filled";
import FluentTableDefault32Filled from "~icons/fluent/table-default-32-filled";

export const MenuIcon = FluentNavigation32Filled;
export const AddIcon = FluentAdd32Filled;
export const EditIcon = FluentEdit32Filled;
export const SaveIcon = FluentSave32Filled;
export const DeleteIcon = FluentDismiss32Filled;
export const GridIcon = FluentTableDefault32Filled;
export const ChevronUpIcon = FluentChevronUp32Filled;
export const ChevronDownIcon = FluentChevronDown32Filled;
export const ChevronLeftIcon = FluentChevronLeft32Filled;
export const ChevronRightIcon = FluentChevronRight32Filled;
export const CollapseIcon = FluentChevronCircleUp32Filled;
export const ExpandIcon = FluentChevronCircleDown32Filled;
export const PinIcon = FluentPin32Filled;
export const UnpinIcon = FluentPinOff32Filled;
